version: "3.9"
services:
  backend:
    build: ./server
    ports:
      - "3000:3000"
    restart: on-failure
    
  frontend:
    build: ./Report-Manager
    ports:
      - "80:80"
    restart: on-failure